version: '3.8'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
        ports:
            - "5000:80"
        depends_on:
            - php
            - mysql
        restart: always
    php:
        build:
            context: .
            dockerfile: ./etc/php/Dockerfile
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - "./web:/var/www/html"
    composer:
        image: composer
        volumes:
            - "./web:/web"
        command: install
        working_dir: /web
    mysql:
        image: mysql:latest
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8888:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./init.sql:/docker-entrypoint-initdb.d/init.sql"